### ISSUE TITLE
Switching layout has impact on other screens

### ISSUE THREAD

**Issue by varakh** [ChWick/gnomesome#2]
Hi,

I am switching layout/cycle between those on my second monitor and the primary one gets also adjusted and moves windows around. Am I doing something wrong here? I thought that layouts are screen independent.

Maybe you should also provide a "default" layout in some kind of settings menu like shellshape does. Would be really nice.

**Comment by ChWick** [comment]
Hi,

the layouts should be completely independent. Can you give an instruction to reproduce this bug?
Unfortunately, gnome seems to have a strange behavior when creating new windows. Sometimes a window has an initial position on monitor 1 but is attached to monitor 2 (location of the mouse), the latter is expected. When reentering the floating layout gnomesome will restore its original position which is why the window is moved to its original position on monitor 1, and monitor 1 will be the new owner. Thus the window will get inserted in the layout of monitor 1...

I took many ideas from shellshape, but gnomesome is far from being complete. I'll try to implement this setting (settings in general)!

**Comment by ChWick** [comment]
Possibly fixed by e4ec4e233636bb0b82c8d75bb321204d6a8d759f aswell
